.386
.MODEL FLAT

.DATA
symbol DB ?
symbolToReplace DB ?
.CODE 

REPLACE_FOR_CURRENT_STRING MACRO
	LOCAL LOOP_FOR_CURRENT_STRING, IS_REPLACE
	LOOP_FOR_CURRENT_STRING:
		MOV EDX, [EAX]
		CMP DL, symbol
		JNE IS_REPLACE
			XOR EDX, EDX
			MOV DL, symbolToReplace
		IS_REPLACE:
			MOV [ESI], DL
			INC ESI
			INC EAX
			CMP EAX, EBX
	JNE LOOP_FOR_CURRENT_STRING
	MOV DL, 10
	MOV [ESI], DL
	INC ESI
ENDM

_REPLACE PROC
	PUSH EBP
	MOV EBP, ESP
	MOV ECX, [EBP]+8
	MOV ESI, [EBP]+12
	MOV EAX, [EBP]+16
	MOV symbol, AL
	XOR EAX, EAX
	MOV EAX, [EBP]+20
	MOV symbolToReplace, AL
	XOR EAX, EAX
	DEC ECX
	IS_END:
		MOV EAX, ECX
		INC EAX
	LOOP_STRINGS:
		INC ECX		
		MOV EDX, [ECX]
		CMP DL, 204
		JE LAST_ITER
		CMP DL, 10
	JNE LOOP_STRINGS
	MOV EBX, ECX
	REPLACE_FOR_CURRENT_STRING
	JMP IS_END
	LAST_ITER:
	MOV EBX, ECX
	REPLACE_FOR_CURRENT_STRING
	POP EBP
	MOV DL, 0
	MOV [ESI], DL
	RET 
_REPLACE ENDP

END
